ALTER TABLE dishes ADD COLUMN signature BOOLEAN DEFAULT 0;
ALTER TABLE dishes ADD COLUMN panel_rank INT DEFAULT NULL;
ALTER TABLE dishes ADD COLUMN popularity INT DEFAULT 0;
ALTER TABLE dishes ADD COLUMN is_featured BOOLEAN DEFAULT 0;
